### Create a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
  "email": "emailtest@test.com",
  "password": "12345"
}

### Sign in with user
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
  "email": "emailtest@test.com",
  "password": "12345"
}

### Find a particular user with a given ID
GET http://localhost:3000/auth/2

### Find all users
GET http://localhost:3000/auth?email=test1@test.com

### Removing a user
DELETE http://localhost:3000/auth/1

### Update a user
PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
  "password": "bye1234"
}

### Set a color
GET http://localhost:3000/auth/colors/red

### Get a color
GET http://localhost:3000/auth/colors